name: TADFGen
channels:
  - pytorch
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=7_kmp_llvm
  - blas=1.0=mkl
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cudatoolkit=11.3.1=hb98b00a_13
  - icu=78.1=h33c6efd_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libcblas=3.9.0=13_h8e06fc2_netlib
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libiconv=1.18=h3b78370_2
  - liblapack=3.9.0=13_h8876d29_netlib
  - liblapacke=3.9.0=13_hb041515_netlib
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libuuid=2.41.3=h5347b49_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=21.1.8=h4922eb0_0
  - mkl=2023.0.0=h84fe81f_26648
  - mkl-devel=2023.0.0=ha770c72_26649
  - mkl-include=2023.0.0=h84fe81f_26648
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - pip=25.2=pyh8b19718_0
  - python=3.9.23=hc30ae73_0_cpython
  - pytorch=1.12.1=py3.9_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.3=h853b02a_0
  - setuptools=80.9.0=pyhff2d567_0
  - tbb=2021.13.0=h8d10470_4
  - tk=8.6.13=noxft_ha0e22de_103
  - typing_extensions=4.14.1=pyhe01879c_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - antlr4-python3-runtime==4.8
      - ase==3.26.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - fonttools==4.60.2
      - hydra-core==1.1.0
      - importlib-resources==6.5.2
      - kiwisolver==1.4.7
      - matplotlib==3.9.4
      - numpy==1.23.5
      - omegaconf==2.1.2
      - packaging==25.0
      - pandas==2.3.3
      - pillow==11.3.0
      - pyparsing==3.3.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - rdkit==2024.9.6
      - scipy==1.13.1
      - six==1.17.0
      - tzdata==2025.3
      - zipp==3.23.0
